repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/codespell-project/codespell
    rev: master
    hooks:
    -   id: codespell
