version: '2'
services:
  scikit:
    build:
      context: ./scikit
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./super:/usr/src/app
      - ./data:/data
    environment:
      - FRAMEWORK=scikit
  pytorch:
    build:
      context: ./pytorch
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./super:/usr/src/app
      - ./data:/data
    environment:
      - FRAMEWORK=pytorch
  tensorflow:
    build:
      context: ./tensorflow
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./super:/usr/src/app
      - ./data:/data
    environment:
      - KERAS_BACKEND=tensorflow
      - FRAMEWORK=keras
      - TF_CPP_MIN_LOG_LEVEL=3
  cntk:
    build:
      context: ./cntk
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./super:/usr/src/app
      - ./data:/data
    environment:
      - KERAS_BACKEND=cntk
      - FRAMEWORK=keras
  theano:
    build:
      context: ./theano
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./super:/usr/src/app
      - ./data:/data
    environment:
      - KERAS_BACKEND=theano
      - FRAMEWORK=keras
      - OMP_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
      - GOTO_NUM_THREADS=4
      - THEANO_FLAGS=blas.ldflags=-lblas,floatX=float32,openmp=True
  mxnet:
    build:
      context: ./mxnet
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./super:/usr/src/app
      - ./data:/data
    environment:
      - KERAS_BACKEND=mxnet
      - FRAMEWORK=keras
  mlpack:
    build:
      context: ./mlpack
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./mlpack:/usr/src/app
      - ./data:/data
    environment:
      - FRAMEWORK=mlpack
  benchmark:
    build:
      context: ./benchmark
      dockerfile: ../docker/python-dockerfile
    volumes:
      - ./benchmark:/usr/src/app
      - ./data:/data
    command: 'python3 -u main.py'
